kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shyamlakkad/backend
        ports:
          - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
               name: secret
              key: key
        - name: PORT
          value: "5001"
