kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shyamlakkad/frontend:10
        ports:
          - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
